const setsArray = [
  'Base',
  'Jungle',
  'Wizards Black Star Promos',
  'Fossil',
  'Base Set 2',
  'Team Rocket',
  'Gym Heroes',
  'Gym Challenge',
  'Neo Genesis',
  'Neo Discovery',
  'Southern Islands',
  'Neo Revelation',
  'Neo Destiny',
  'Legendary Collection',
  'Expedition Base Set',
  'Aquapolis',
  'Skyridge',
  'Ruby & Sapphire',
  'Sandstorm',
  'Dragon',
  'Nintendo Black Star Promos',
  'Team Magma vs Team Aqua',
  'Hidden Legends',
  'FireRed & LeafGreen',
  'POP Series 1',
  'Team Rocket Returns',
  'Deoxys',
  'Emerald',
  'Unseen Forces',
  'POP Series 2',
  'Delta Species',
  'Legend Maker',
  'POP Series 3',
  'Holon Phantoms',
  'Crystal Guardians',
  'POP Series 4',
  'Dragon Frontiers',
  'POP Series 5',
  'Power Keepers',
  'Diamond & Pearl',
  'DP Black Star Promos',
  'Mysterious Treasures',
  'POP Series 6',
  'Secret Wonders',
  'Great Encounters',
  'POP Series 7',
  'Majestic Dawn',
  'Legends Awakened',
  'POP Series 8',
  'Stormfront',
  'Platinum',
  'POP Series 9',
  'Rising Rivals',
  'Supreme Victors',
  'Arceus',
  'Pokémon Rumble',
  'HeartGold & SoulSilver',
  'HGSS Black Star Promos',
  'HS—Unleashed',
  'HS—Undaunted',
  'HS—Triumphant',
  'Call of Legends',
  'BW Black Star Promos',
  'Black & White',
  "McDonald's Collection 2011",
  'Emerging Powers',
  'Noble Victories',
  'Next Destinies',
  'Dark Explorers',
  "McDonald's Collection 2012",
  'Dragons Exalted',
  'Dragon Vault',
  'Boundaries Crossed',
  'Plasma Storm',
  'Plasma Freeze',
  'Plasma Blast',
  'XY Black Star Promos',
  'Legendary Treasures',
  'Kalos Starter Set',
  'XY',
  'Flashfire',
  'Furious Fists',
  'Phantom Forces',
  'Primal Clash',
  'Double Crisis',
  'Roaring Skies',
  'Ancient Origins',
  'BREAKthrough',
  'BREAKpoint',
  'Generations',
  'Fates Collide',
  'Steam Siege',
  "McDonald's Collection 2016",
  'Evolutions',
  'Sun & Moon',
  'SM Black Star Promos',
  'Guardians Rising',
  'Burning Shadows',
  'Shining Legends',
  'Crimson Invasion',
  'Ultra Prism',
  'Forbidden Light',
  'Celestial Storm',
  'Dragon Majesty',
  'Lost Thunder',
  'Team Up',
  'Detective Pikachu',
  'Unbroken Bonds',
  'Unified Minds',
  'Hidden Fates',
  'Shiny Vault',
  "McDonald's Collection 2019",
  'Cosmic Eclipse',
  'SWSH Black Star Promos',
  'Sword & Shield',
  'Rebel Clash',
  'Darkness Ablaze',
  "Champion's Path",
  'Vivid Voltage',
  'Shining Fates',
  'Shiny Vault',
  'Battle Styles',
  'Chilling Reign'
]
export default setsArray
